db:
    image: postgres
    volumes:
        - "./docker_data:/var/lib/postgresql/data"
web:
    image: littleq0903/ntpc-social-frontdesk-center
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
        - "./docker_media:/src/ntpc_frontdesk/media"
    ports:
        - "80:8000"
    links:
        - db

