db:
    image: postgres
    volumes:
        - "./docker_data:/var/lib/postgresql/data"
web:
    image: littleq0903/ntpc-frontdesk:1.0
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
        - "./docker_media:ntpc_frontdesk/media"
    ports:
        - "80:8000"
    links:
        - db
